import { NextRequest, NextResponse } from "next/server";
import prisma from "~/lib/prisma";
import { validateToken } from "~/server/trpc/utils/fuzzing";
import { getAdapter } from "~/server/connectors/registry";
import {
  extractMessage,
  extractOccurredAt,
  extractSeverity,
  extractSource,
  flattenJsonLog,
  type IngestRecord,
} from "~/server/connectors/normalize";

const MAX_RECORDS = 500;

/**
 * Log intake for AGENT-mode integrations.
 *
 * The host authenticates with the bearer token embedded in the install script
 * generated by `integrations.installScript`, so each product gets its own
 * credential and re-issuing a script revokes the previous one.
 */
export async function POST(request: NextRequest) {
  const authorization = request.headers.get("authorization");
  const adapterKey = request.headers.get("x-integration-key");

  if (!authorization?.startsWith("Bearer ") || !adapterKey) {
    return NextResponse.json(
      { error: "Missing Authorization or X-Integration-Key header" },
      { status: 401 }
    );
  }

  if (!getAdapter(adapterKey)) {
    return NextResponse.json(
      { error: `Unknown integration: ${adapterKey}` },
      { status: 404 }
    );
  }

  const integration = await prisma.integration.findUnique({
    where: { adapterKey },
  });

  if (!integration?.ingestTokenHash) {
    return NextResponse.json(
      { error: "Integration has no ingest token; regenerate the install script" },
      { status: 401 }
    );
  }

  const token = authorization.slice("Bearer ".length);
  if (!validateToken(token, integration.ingestTokenHash)) {
    return NextResponse.json({ error: "Invalid token" }, { status: 401 });
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const records: IngestRecord[] = (Array.isArray(body) ? body : [body]).filter(
    (item): item is IngestRecord =>
      typeof item === "object" && item !== null && !Array.isArray(item)
  );

  if (records.length === 0) {
    return NextResponse.json(
      { error: "Body contained no records" },
      { status: 400 }
    );
  }

  if (records.length > MAX_RECORDS) {
    return NextResponse.json(
      { error: `Batch too large: ${records.length} > ${MAX_RECORDS}` },
      { status: 413 }
    );
  }

  await prisma.collectedLog.createMany({
    data: records.map((original) => {
      // Zeek and other NDJSON tails arrive with the object stringified in `log`.
      const record = flattenJsonLog(original);
      return {
        integrationId: integration.id,
        source: extractSource(record, adapterKey),
        severity: extractSeverity(record),
        message: extractMessage(record),
        occurredAt: extractOccurredAt(record),
        raw: record as never,
      };
    }),
  });

  // First delivery is what flips an agent integration from 설치 대기 to 정상.
  await prisma.integration.update({
    where: { id: integration.id },
    data: { status: "CONNECTED", lastError: null, lastSyncAt: new Date() },
  });

  return NextResponse.json({ accepted: records.length });
}
